### ISSUE TITLE
I can't find the snippets in the library next day after installing and using once.

### ISSUE THREAD

**Issue by amit2908** [DominatorVbN/MarkdownCodeSnippets#1]
Is there any script that needs to be run to install them everytime I open the Xcode?

**Comment by DominatorVbN** [comment]
no! you just have to add them once!
Could you check `~/Library/Developer/Xcode/UserData/CodeSnippets` this directory in your mac if the snippets were copied also are you using multiple versions fo XCodes?

**Comment by amit2908** [comment]
@DominatorVbN Yes I do have 2 Xcode but what can I do if I need both of them?
Its not working on both currently.

**Comment by DominatorVbN** [comment]
@amit2908 yeah there is issue of directory getting cleaned every time you switch between Xcode,
Workaround is every time you switch XCode just copy them again. There is nothing in my knowledge we can do about that.

**Comment by DominatorVbN** [comment]
Hey @amit2908, I am closing this issue if you are having any other issue please feel free to open another issue.
